timetracker/timetracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'', include('trackers.urls', namespace='trackers')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls', namespace='users')),
]

timetracker/trackers/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_activity/$', login_required(views.ActivityCreate.as_view()), name='add_activity'),
    url(r'^add_duration/(?P<activity_id>\d+)/$', views.add_duration,
        name='add_duration'),
]

timetracker/users/urls.py
"""Определяет схемы URL для пользователей"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Страница входа
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # Страница регистрации
    url(r'^register/$', views.register, name='register'),
]

timetracker/trackers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Activity(models.Model):
    """a business that makes user))"""
    WORK_VALUE = 'W'
    WORK_LABEL = 'work'
    OTHER_VALUE = 'O'
    OTHER_LABEL = 'other'

    title = models.CharField(max_length=30)
    TYPE_CHOICES = models.CharField(
        max_length=1, choices=((WORK_VALUE, WORK_LABEL), (OTHER_VALUE, OTHER_LABEL)), default='W')
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = "Activities"

    def total_duration(self):
        total_duration_sum = self.activity_time_spend.all().aggregate(Sum('time_spent'))
        return total_duration_sum['time_spent__sum']

    def __str__(self):
        return self.title


class TimeSpend(models.Model):
    """ time spent on activities by dates"""
    activity = models.ForeignKey(
        Activity, on_delete=models.CASCADE, related_name='activity_time_spend')
    date = models.DateTimeField()
    time_spent = models.PositiveIntegerField()

    def work_activity_time_sum(self, user):
        time_sum = TimeSpend.objects.filter(activity__owner=user).\
            filter(activity__TYPE_CHOICES=Activity.WORK_VALUE).aggregate(Sum('time_spent'))
        return time_sum['time_spent__sum']

    def other_activity_time_sum(self, user):
        time_sum = TimeSpend.objects.filter(activity__owner=user).\
            filter(activity__TYPE_CHOICES=Activity.OTHER_VALUE).aggregate(Sum('time_spent'))
        return time_sum['time_spent__sum']

    def all_activity_time(self, user):
        time_sum = TimeSpend.objects.filter(activity__owner=user).aggregate(Sum('time_spent'))
        return time_sum['time_spent__sum']

    def percentage(self, user):
        other = self.other_activity_time_sum(user)
        work = self.work_activity_time_sum(user)

        if work and other:
            result = work * 100 / (work + other)
            return float("{0:.1f}".format(result))
        elif work:
            return 100
        else:
            return 0

timetracker/users/models.py
from django.db import models

# Create your models here.

timetracker/trackers/forms.py
from django import forms
from .models import Activity, TimeSpend


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', "TYPE_CHOICES", ]

    def set_owner(self, request):
        new_activity = self.save(commit=False)
        new_activity.owner = request.user


class TimeSpendForm(forms.ModelForm):
    class Meta:
        model = TimeSpend
        fields = ['date', 'time_spent']
        labels = {'time_spent': 'add duration in hours:'}
        widgets = {'time_spent': forms.NumberInput(),
                   'date': forms.SelectDateWidget(),
                   }

    def set_activity(self, activity):
        new_time_spend = self.save(commit=False)
        new_time_spend.activity = activity

timetracker/trackers/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView

from .models import Activity, TimeSpend
from .forms import ActivityForm, TimeSpendForm

time = TimeSpend()


def check_owner(request, activity):
    if activity.owner != request.user:
        raise Http404


@login_required()
def index(request):
    """homepage with activities"""
    activities = Activity.objects.filter(owner=request.user).order_by('date_added')
    user = request.user
    work_statistic = time.work_activity_time_sum(user)
    other_statistic = time.other_activity_time_sum(user)
    percentage_w_to_all = time.percentage(user)
    all_time = time.all_activity_time(user)
    return render(request, 'trackers/index.html', {
        'activities': activities,
        'work_statistic': work_statistic,
        'other_statistic': other_statistic,
        'percentage_w_to_all': percentage_w_to_all,
        'all_time': all_time,
    })


class ActivityCreate(FormView):
    template_name = 'trackers/add_activity.html'
    form_class = ActivityForm

    def form_valid(self, form):
        form.set_owner(self.request)
        form.save()
        return HttpResponseRedirect(reverse('trackers:index'))


@login_required()
def add_duration(request, activity_id):
    activity = get_object_or_404(Activity, id=activity_id)
    check_owner(request, activity)
    if request.method == 'POST':
        form = TimeSpendForm(request.POST)
        if form.is_valid():
            form.set_activity(activity)
            form.save()
            return HttpResponseRedirect(reverse('trackers:index'))
    else:
        form = TimeSpendForm()

    return render(request, 'trackers/add_duration.html', {'activity': activity, 'form': form})

timetracker/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """ logout """
    logout(request)
    return HttpResponseRedirect(reverse('trackers:index'))

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(
                    username=new_user.username,
                    password=request.POST['password1']
                    )
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('trackers:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

timetracker/trackers/templates/trackers/add_activity.html
{% extends "trackers/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Add a new activity:</h2>
{% endblock header %}
{% block content %}
<form action="{% url 'trackers:add_activity' %}" method="post" class="form">
     {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button name="submit" class="btn btn-primary">add</button>
      {% endbuttons %}
</form>

{% endblock content %}

timetracker/trackers/templates/trackers/add_duration.html
{% extends "trackers/base.html" %}
{% load bootstrap3 %}
{% load l10n %}
{% block content %}
{% localize on %}
<h3>{{ activity.title}}</h3>
<form action="{% url 'trackers:add_duration' activity.id %}"
      method="post" class="form">
     {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button name="submit" class="btn btn-primary">add</button>
      {% endbuttons %}
</form>
{% endlocalize %}
{% endblock content %}

timetracker/trackers/templates/trackers/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Time Tracker</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
<!-- Статическая навигационная панель -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'trackers:index' %}">
              Time Tracker</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>

          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
              {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">log in</a></li>
              {% endif %}
          </ul>
      </div><!--/.nav-collapse -->
  </div>
</nav>
    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->
  </body>
</html>

timetracker/trackers/templates/trackers/index.html
{% extends "trackers/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <div class='jumbotron'>
    <h2>Track your activities.</h2>
  </div>
{% endblock header %}

{% block content %}
  <h2>
      Your current activities:
  </h2>
<p>
    {% for activity in activities %}
        <li>
           {{ activity.title }}
           {{ activity.date_added|date:'M d, Y H:i'  }}
           <p> type:{{ activity.TYPE_CHOICES }}</p>
           <p>time spent: {{ activity.total_duration|default:0 }} h.</p>

           <a href="{% url 'trackers:add_duration' activity.id %}">add duration</a>

        </li>
    {% empty %}
      <li>No activities have been added yet.</li>
    {% endfor %}
</ul>
<h4><a href="{% url 'trackers:add_activity' %}">add new activity</a></h4>

<div class='jumbotron'>
    <h2>See your statistic.</h2>
  </div>
<h3>Time spent: {{ all_time|default:0 }} h.</h3>
<h3>Time spent on work: {{ work_statistic|default:0 }} h.</h3>
<h3>Time spent on other activities:{{ other_statistic|default:0 }} h.</h3>
<h3>Percentage of work to all time: {{ percentage_w_to_all|default:0 }}%</h3>

{% endblock content %}

timetracker/users/templates/users/login.html
{% extends "trackers/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  
  <form method="post" action="{% url 'users:login' %}" class="form">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'trackers:index' %}" />
  </form>

{% endblock content %}

timetracker/users/templates/users/register.html
{% extends "trackers/base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'trackers:index' %}" />
    </form>
{% endblock content %}